// ============================================
// JOB DATA - 60 Realistic Indian Tech Jobs
// ============================================

const jobsData = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "DSA", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://amazon.jobs/intern-sde",
        description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems and learn from experienced engineers. Strong foundation in data structures and algorithms required. 6-month internship with potential for full-time conversion."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Infosys is hiring fresh graduates for our GET program. Comprehensive training provided in latest technologies. Work on client projects across domains. Excellent learning opportunities and career growth. BE/BTech in CS/IT/ECE preferred."
    },
    {
        id: 3,
        title: "Frontend Developer Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://razorpay.com/jobs/frontend-intern",
        description: "Build beautiful payment interfaces at Razorpay. Work with React and modern frontend tools. Collaborate with designers and backend teams. Fast-paced fintech environment. Prior internship or project experience preferred."
    },
    {
        id: 4,
        title: "Java Developer",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3–5 LPA",
        applyUrl: "https://tcs.com/careers/java-dev",
        description: "TCS Digital is looking for Java developers to work on enterprise applications. Build microservices using Spring Boot. Work with global clients. Training provided on latest frameworks. Good communication skills essential."
    },
    {
        id: 5,
        title: "Python Developer (Fresher)",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "REST API"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://wipro.com/careers/python",
        description: "Join Wipro's AI and automation team. Develop backend services using Python and Django. Work on machine learning pipelines. Exposure to cloud technologies. Strong programming fundamentals required. Fresh graduates welcome."
    },
    {
        id: 6,
        title: "React Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript", "Node.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "https://swiggy.com/careers/react-dev",
        description: "Build features for millions of Swiggy users. Work on complex state management and performance optimization. Collaborate with product and design teams. Fast-paced startup environment. 1-3 years of React experience required."
    },
    {
        id: 7,
        title: "QA Automation Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Testing"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://flipkart.com/careers/qa-intern",
        description: "Learn automation testing at India's largest e-commerce platform. Write test scripts using Selenium and Java. Work with CI/CD pipelines. Mentorship from senior QA engineers. 6-month internship program."
    },
    {
        id: 8,
        title: "Data Analyst Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["SQL", "Python", "Excel", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://phonepe.com/careers/data-intern",
        description: "Analyze payment trends and user behavior at PhonePe. Create dashboards and reports. Work with large datasets. Learn from data science team. Strong analytical skills and SQL knowledge required."
    },
    {
        id: 9,
        title: "Backend Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "MongoDB", "AWS", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://cred.club/careers/backend",
        description: "Build scalable backend systems for CRED's fintech platform. Design APIs and microservices. Work with modern tech stack. High ownership and impact. 1-3 years backend experience with Node.js or similar."
    },
    {
        id: 10,
        title: "Full Stack Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["JavaScript", "React", "Node.js", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–6 LPA",
        applyUrl: "https://zoho.com/careers/fullstack",
        description: "Develop features for Zoho's suite of business applications. Work on both frontend and backend. Learn multiple technologies. Great work-life balance. 0-1 years of experience in web development."
    },
    {
        id: 11,
        title: "DevOps Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "Jenkins", "AWS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://paytm.com/careers/devops-intern",
        description: "Learn DevOps practices at Paytm. Work on CI/CD pipelines and cloud infrastructure. Automate deployment processes. Exposure to containerization and orchestration. Basic Linux and scripting knowledge required."
    },
    {
        id: 12,
        title: "Android Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–14 LPA",
        applyUrl: "https://juspay.in/careers/android",
        description: "Build payment SDKs used by millions. Work on Android architecture and performance. Collaborate with product teams. Fintech domain experience. 1-3 years of Android development with Kotlin."
    },
    {
        id: 13,
        title: "Software Engineer Trainee",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.5–4 LPA",
        applyUrl: "https://capgemini.com/careers/trainee",
        description: "Join Capgemini's engineering excellence program. Structured training in enterprise technologies. Work on global projects. Mentorship and certification opportunities. BE/BTech from recognized universities."
    },
    {
        id: 14,
        title: "UI/UX Developer Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Figma", "HTML", "CSS", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://freshworks.com/careers/ui-intern",
        description: "Design and develop user interfaces for SaaS products. Work closely with design team. Implement responsive designs. Learn design systems. Portfolio or project work required."
    },
    {
        id: 15,
        title: "Machine Learning Intern",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "ML Algorithms"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://ibm.com/careers/ml-intern",
        description: "Work on AI and ML projects at IBM Research. Implement machine learning models. Research and development opportunities. Academic background in ML/AI preferred. 6-month research internship."
    },
    {
        id: 16,
        title: "Cloud Engineer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Azure", "Terraform", "Kubernetes"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://accenture.com/careers/cloud",
        description: "Design and implement cloud solutions for enterprise clients. Work with AWS and Azure. Infrastructure as code using Terraform. Container orchestration. 1-3 years cloud experience with certifications preferred."
    },
    {
        id: 17,
        title: "Golang Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "Microservices", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://razorpay.com/careers/golang",
        description: "Build high-performance payment systems using Go. Design microservices architecture. Handle millions of transactions. Work with distributed systems. 1-3 years backend experience, Go knowledge preferred."
    },
    {
        id: 18,
        title: "Data Engineer",
        company: "Cognizant",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "SQL", "Spark", "ETL"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://cognizant.com/careers/data-engineer",
        description: "Build data pipelines and ETL processes. Work with big data technologies. Data warehousing and analytics. Training provided on Spark and cloud platforms. 0-1 years experience in data domain."
    },
    {
        id: 19,
        title: "iOS Developer Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Swift", "iOS SDK", "UIKit"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://swiggy.com/careers/ios-intern",
        description: "Develop features for Swiggy's iOS app. Learn mobile architecture patterns. Work with experienced iOS team. Fast-paced environment. Prior iOS project or app development experience preferred."
    },
    {
        id: 20,
        title: "Cybersecurity Analyst",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Network Security", "Penetration Testing", "SIEM"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "7–12 LPA",
        applyUrl: "https://oracle.com/careers/security",
        description: "Protect Oracle's cloud infrastructure. Conduct security assessments and penetration testing. Incident response and threat analysis. Security certifications valued. 1-3 years in cybersecurity or related field."
    },
    {
        id: 21,
        title: "Graduate Trainee Engineer",
        company: "SAP",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "ABAP", "SAP Modules"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "4.5–6 LPA",
        applyUrl: "https://sap.com/careers/gte",
        description: "Join SAP's graduate program. Learn enterprise software development. Work on SAP products and solutions. Comprehensive training program. Global exposure. BE/BTech with strong academics."
    },
    {
        id: 22,
        title: "Frontend Engineer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "JavaScript", "Redux", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://phonepe.com/careers/frontend",
        description: "Build user interfaces for India's leading payment app. Performance optimization and scalability. Work with product and design teams. High impact role. 1-3 years frontend development experience."
    },
    {
        id: 23,
        title: "Blockchain Developer Intern",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Solidity", "Ethereum", "Web3.js"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://polygon.technology/careers/blockchain-intern",
        description: "Work on blockchain protocols and smart contracts. Learn Web3 development. Contribute to open-source projects. Cutting-edge technology. Strong programming background and interest in blockchain required."
    },
    {
        id: 24,
        title: "Technical Support Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Troubleshooting", "Linux", "Networking"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://dell.com/careers/support",
        description: "Provide technical support for Dell products and services. Troubleshoot hardware and software issues. Customer interaction and problem-solving. Training provided. Good communication skills essential."
    },
    {
        id: 25,
        title: "Product Analyst Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Analytics", "Excel", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://cred.club/careers/product-analyst-intern",
        description: "Analyze product metrics and user behavior. Support product decisions with data. Create reports and dashboards. Work with product managers. Strong analytical and communication skills required."
    },
    {
        id: 26,
        title: "Backend Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Kafka", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "10–18 LPA",
        applyUrl: "https://flipkart.com/careers/backend",
        description: "Build scalable e-commerce systems. Design APIs and microservices. Handle high traffic and transactions. Work with distributed systems. 1-3 years backend development experience with Java."
    },
    {
        id: 27,
        title: "React Native Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://zomato.com/careers/react-native",
        description: "Develop cross-platform mobile apps for Zomato. Build features for millions of users. Performance optimization. Work with product teams. 1-3 years mobile development experience."
    },
    {
        id: 28,
        title: "Software Developer Trainee",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Java", "DSA"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.25–4 LPA",
        applyUrl: "https://techmahindra.com/careers/trainee",
        description: "Join Tech Mahindra's development team. Training in enterprise technologies. Work on telecom and IT projects. Global client exposure. BE/BTech graduates preferred."
    },
    {
        id: 29,
        title: "AI/ML Engineer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "PyTorch", "ML Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://amazon.jobs/ml-engineer",
        description: "Build ML models for Amazon's recommendation systems. Work on computer vision and NLP. Research and production deployment. 1-3 years ML experience with strong fundamentals."
    },
    {
        id: 30,
        title: "Quality Assurance Engineer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Manual Testing", "Selenium", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://zoho.com/careers/qa",
        description: "Test Zoho's software products. Manual and automation testing. Write test cases and scripts. Bug tracking and reporting. 0-1 years testing experience or fresh graduates with testing knowledge."
    },
    {
        id: 31,
        title: "Site Reliability Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Linux", "Kubernetes", "Monitoring", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        applyUrl: "https://razorpay.com/careers/sre",
        description: "Ensure reliability of payment infrastructure. Build monitoring and alerting systems. Incident management. Work with distributed systems. 1-3 years SRE or DevOps experience."
    },
    {
        id: 32,
        title: "Business Analyst Intern",
        company: "Accenture",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Excel", "SQL", "Communication", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://accenture.com/careers/ba-intern",
        description: "Analyze business requirements and processes. Create documentation and reports. Work with consulting teams. Client interaction. Strong analytical and communication skills required."
    },
    {
        id: 33,
        title: "Embedded Systems Engineer",
        company: "Bosch",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["C", "Embedded C", "Microcontrollers", "RTOS"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://bosch.com/careers/embedded",
        description: "Develop embedded software for automotive systems. Work with microcontrollers and sensors. Real-time operating systems. Hardware-software integration. ECE/EEE background preferred."
    },
    {
        id: 34,
        title: "Content Developer Intern",
        company: "Byju's",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Content Writing", "Research", "Communication"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://byjus.com/careers/content-intern",
        description: "Create educational content for learning platform. Research and write technical topics. Collaborate with subject experts. Good writing and communication skills. Background in education or tech preferred."
    },
    {
        id: 35,
        title: "Flutter Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Flutter", "Dart", "Mobile Development", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–15 LPA",
        applyUrl: "https://meesho.com/careers/flutter",
        description: "Build cross-platform apps for social commerce. Develop features for millions of users. Performance and scalability. Work with product teams. 1-3 years Flutter or mobile development experience."
    },
    {
        id: 36,
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Networking", "CCNA", "Routing", "Switching"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "4–6 LPA",
        applyUrl: "https://cisco.com/careers/network",
        description: "Configure and maintain network infrastructure. Work with routers and switches. Troubleshoot network issues. CCNA certification preferred. 0-1 years networking experience."
    },
    {
        id: 37,
        title: "Salesforce Developer",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Salesforce", "Apex", "Visualforce", "Lightning"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "https://deloitte.com/careers/salesforce",
        description: "Develop and customize Salesforce applications. Work on CRM implementations. Client-facing role. Salesforce certifications valued. 1-3 years Salesforce development experience."
    },
    {
        id: 38,
        title: "Game Developer Intern",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Unity", "C#", "Game Development"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://dream11.com/careers/game-intern",
        description: "Develop gaming features for fantasy sports platform. Work with Unity engine. Learn game mechanics and optimization. Portfolio or game projects required. 6-month internship."
    },
    {
        id: 39,
        title: "Database Administrator",
        company: "Oracle",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Oracle DB", "SQL", "PL/SQL", "Performance Tuning"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "6–11 LPA",
        applyUrl: "https://oracle.com/careers/dba",
        description: "Manage and optimize Oracle databases. Performance tuning and troubleshooting. Backup and recovery. Work with enterprise clients. 1-3 years DBA experience with Oracle certification preferred."
    },
    {
        id: 40,
        title: "Research Intern",
        company: "Microsoft Research",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Research", "ML", "Mathematics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://microsoft.com/research/intern",
        description: "Work on cutting-edge research projects in AI and ML. Publish papers and contribute to open source. Collaborate with researchers. Strong academic background required. PhD students preferred."
    },
    {
        id: 41,
        title: "ETL Developer",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Informatica", "SQL", "Data Warehousing"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://infosys.com/careers/etl",
        description: "Develop ETL processes for data integration. Work with Informatica and SQL. Data warehousing projects. Client interaction. 0-1 years experience in data domain or fresh graduates."
    },
    {
        id: 42,
        title: "Security Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Application Security", "OWASP", "Penetration Testing"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://paytm.com/careers/security",
        description: "Secure Paytm's payment infrastructure. Conduct security audits and penetration testing. Vulnerability assessment. Work with development teams. 1-3 years application security experience."
    },
    {
        id: 43,
        title: "Technical Writer Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Technical Writing", "Documentation", "Communication"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "₹18k–₹28k/month Internship",
        applyUrl: "https://freshworks.com/careers/writer-intern",
        description: "Create technical documentation for SaaS products. Write user guides and API documentation. Work with engineering teams. Good writing skills and technical aptitude required."
    },
    {
        id: 44,
        title: "Full Stack Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "MongoDB", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://ola.com/careers/fullstack",
        description: "Build features for Ola's mobility platform. Work on web and backend systems. Scalability and performance. Fast-paced environment. 1-3 years full stack development experience."
    },
    {
        id: 45,
        title: "Automation Tester",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Selenium", "Java", "TestNG", "CI/CD"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://capgemini.com/careers/automation",
        description: "Automate testing for enterprise applications. Write test scripts using Selenium. Integrate with CI/CD pipelines. 0-1 years testing experience or strong automation knowledge."
    },
    {
        id: 46,
        title: "AR/VR Developer Intern",
        company: "Nvidia",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Unity", "C#", "3D Graphics", "AR/VR"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://nvidia.com/careers/ar-vr-intern",
        description: "Develop AR/VR applications and experiences. Work with Unity and graphics programming. Research and prototyping. Strong 3D graphics knowledge. Portfolio required."
    },
    {
        id: 47,
        title: "ServiceNow Developer",
        company: "TCS",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["ServiceNow", "JavaScript", "ITIL"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "5–9 LPA",
        applyUrl: "https://tcs.com/careers/servicenow",
        description: "Develop and customize ServiceNow applications. ITSM implementations. Work with global clients. ServiceNow certifications preferred. 1-3 years ServiceNow experience."
    },
    {
        id: 48,
        title: "Kotlin Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Kotlin", "Android", "Java", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "5–8 LPA",
        applyUrl: "https://juspay.in/careers/kotlin",
        description: "Develop payment SDKs using Kotlin. Work on Android and backend systems. Fintech domain. Learn from experienced team. 0-1 years Kotlin or Java development."
    },
    {
        id: 49,
        title: "Performance Engineer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["JMeter", "Performance Testing", "Monitoring"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "7–12 LPA",
        applyUrl: "https://swiggy.com/careers/performance",
        description: "Ensure performance and scalability of Swiggy's platform. Load testing and optimization. Work with engineering teams. 1-3 years performance testing experience."
    },
    {
        id: 50,
        title: "Scrum Master",
        company: "Cognizant",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Agile", "Scrum", "Jira", "Communication"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://cognizant.com/careers/scrum-master",
        description: "Facilitate agile ceremonies and remove blockers. Work with development teams. CSM certification preferred. 1-3 years experience in agile environments."
    },
    {
        id: 51,
        title: "Graphics Designer Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Photoshop", "Illustrator", "Design", "Creativity"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://zomato.com/careers/design-intern",
        description: "Create visual content for marketing campaigns. Design graphics for app and web. Work with marketing team. Portfolio required. 6-month internship."
    },
    {
        id: 52,
        title: "SAP ABAP Developer",
        company: "Wipro",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["ABAP", "SAP", "OOPS", "SQL"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4–6 LPA",
        applyUrl: "https://wipro.com/careers/sap-abap",
        description: "Develop SAP applications using ABAP. Work on enterprise implementations. Training provided. 0-1 years SAP experience or fresh graduates with SAP knowledge."
    },
    {
        id: 53,
        title: "Blockchain Engineer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–30 LPA",
        applyUrl: "https://polygon.technology/careers/blockchain",
        description: "Build blockchain protocols and infrastructure. Develop smart contracts. Work on Layer 2 solutions. Cutting-edge Web3 technology. 1-3 years blockchain development experience."
    },
    {
        id: 54,
        title: "Video Editor Intern",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Premiere Pro", "After Effects", "Video Editing"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://unacademy.com/careers/video-intern",
        description: "Edit educational videos for online courses. Work with content creators. Learn video production. Portfolio or sample work required. 6-month internship."
    },
    {
        id: 55,
        title: "RPA Developer",
        company: "Accenture",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["UiPath", "Automation Anywhere", "Python"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "4–6.5 LPA",
        applyUrl: "https://accenture.com/careers/rpa",
        description: "Develop robotic process automation solutions. Work with UiPath or Automation Anywhere. Automate business processes. Training provided. 0-1 years RPA experience."
    },
    {
        id: 56,
        title: "Systems Engineer",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Programming", "Problem Solving", "Communication"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.6–4.2 LPA",
        applyUrl: "https://infosys.com/careers/systems-engineer",
        description: "Join Infosys as Systems Engineer. Comprehensive training program. Work on diverse projects. Global opportunities. BE/BTech/MCA from recognized universities."
    },
    {
        id: 57,
        title: "Digital Marketing Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["SEO", "Social Media", "Analytics", "Content"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://flipkart.com/careers/marketing-intern",
        description: "Support digital marketing campaigns. SEO and social media management. Analytics and reporting. Learn e-commerce marketing. 6-month internship."
    },
    {
        id: 58,
        title: "Penetration Tester",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Ethical Hacking", "Penetration Testing", "Security Tools"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "8–15 LPA",
        applyUrl: "https://ibm.com/careers/pentester",
        description: "Conduct security assessments and penetration testing. Identify vulnerabilities. Work with security team. CEH or OSCP certification preferred. 1-3 years security testing experience."
    },
    {
        id: 59,
        title: "Data Scientist",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "R", "ML", "Statistics", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–22 LPA",
        applyUrl: "https://amazon.jobs/data-scientist",
        description: "Build predictive models and analytics solutions. Work on recommendation systems. A/B testing and experimentation. 1-3 years data science experience with strong statistics background."
    },
    {
        id: 60,
        title: "Technical Recruiter Intern",
        company: "Google",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Communication", "Recruitment", "Interviewing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://google.com/careers/recruiter-intern",
        description: "Support technical hiring process. Screen candidates and coordinate interviews. Learn recruitment best practices. Strong communication skills. Interest in HR and technology."
    }
];

// Export for use in app
if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobsData;
}
